name: Publish

on:
  workflow_dispatch:

env:
  PKG_VERSION: ""
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          scope: "@svta"

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Publish
        run: npm run pub

      # - name: Get Version
      #   run: echo "PKG_VERSION=`node -p "require('./package').version"`" >> $GITHUB_ENV

      # - name: Create Release Notes
      #   run: npm run notes

      # - name: Draft Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_ACTIONS }}
      #   with:
      #     tag_name: v${{ env.PKG_VERSION }}
      #     release_name: ${{ env.PKG_VERSION }}
      #     commitish: main
      #     body_path: ./RELEASE.md
      #     draft: true
      #     prerelease: false

      # - name: Build Docs
      #   run: npm run build -w docs

      # - name: Deploy Docs
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./docs/dist/
      #     personal_token: ${{ secrets.GH_ACTIONS }}
